#!/bin/bash

#Get absolute location of the runOCP script
my_loc=$(dirname "$(readlink -f "$0")")

usage="$(basename "$0") [-h] [-g] <OCP File> -- Compile and run an OCP problem

where:
    -h  show this help text
    -g  compile with debugging on"

debug="-O3"
while getopts ':hg' option; do
  case "$option" in
    h) echo "$usage"
       exit
       ;;
    g) debug="-g"
       ;;
   \?) printf "illegal option: -%s\n" "$OPTARG" >&2
       echo "$usage" >&2
       exit 1
       ;;
  esac
done
shift $((OPTIND - 1))

#No command line arguments: output help text
if [ $# -eq 0 ]; then
  echo "$usage"
  exit
fi

#Check if the script the user wants to run exists
if [ ! -e "$1" ]
then
  echo "'$1' does not exist!"
  exit
fi

#Get checksum of file so we can see if a compiled version of it exists
checksum="$(md5sum $1 | cut -d ' ' -f 1)"

echo "Checksum: $checksum"

#Check if a compiled copy of the script exists. If not, then make it.
if [ ! -e "/tmp/$checksum.exe" ]; then
  echo "Building program"
  cat $my_loc/src/_ocp_template_c_ > "/tmp/$checksum.c"
  cat $1 >> "/tmp/$checksum.c"
  echo } >> "/tmp/$checksum.c"
  echo "Compiling program"
  g++ $debug -Wall -I $my_loc/src/ -o /tmp/$checksum.exe /tmp/$checksum.c $my_loc/src/*.o -lc -lm --std=c++11
else
  echo "Using cached version of program"
fi

/tmp/$checksum.exe
